package com.business.validation;

public abstract class Constants {
	
	public static final String EXCEPTION_PARTY_DOES_NOT_EXIST = "PARTY_DOES_NOT_EXIST";
	public static final String EXCEPTION_BAD_PAYLOAD_EXCEPTION = "BAD_PAYLOAD_EXCEPTION";
	public static final String EXCEPTION_INVALID_INVOICE_NUMBER_EXCEPTION = "INVALID_INVOICE_NUMBER";
	public static final String EXCEPTION_MULTIPLE_BILLS_FOUND_WITH_SAME_INVOICE_NUMBER = "MULTIPLE_BILLS_FOUND_WITH_SAME_INVOICE_NUMBER";
	public static final String EXCEPTION_INVALID_INVOICE_NUMBER = "INVALID_INVOICE_NUMBER";
	public static final String EXCEPTION_INVALID_BILL_ID = "INVALID_BILL_ID";
	public static final String EXCEPTION_PARTY_NAME_ALREADY_EXISTS = "PARTY_NAME_ALREADY_EXISTS";
	public static final String EXCEPTION_CONSTRAINT_VIOLATION_EXCEPTION = "CONSTRAINT_VIOLATION_EXCEPTION";
	
	
	public static final String QUERY_GET_BILL_BY_INVOICE_NUMBER = "GET_BILL_BY_INVOICE_NUMBER";
	public static final String QUERY_GET_BILLS_BY_PARTY_ID = "GET_BILLS_BY_PARTY_ID";
	public static final String QUERY_GET_TRANSACTIONS_BY_PARTY_ID = "GET_TRANSACTIONS_BY_PARTY_ID";
	public static final String QUERY_GET_PURCHASE_AMOUNT_BY_PARTY_ID = "GET_PURCHASE_AMOUNT_BY_PARTY_ID";
	public static final String QUERY_GET_SALE_AMOUNT_BY_PARTY_ID = "GET_SALE_AMOUNT_BY_PARTY_ID";
	public static final String QUERY_GET_PAYMENT_RECEIVED_AMOUNT_BY_PARTY_ID = "GET_PAYMENT_RECEIVED_AMOUNT_BY_PARTY_ID";
	public static final String QUERY_GET_PAYMENT_MADE_AMOUNT_BY_PARTY_ID = "GET_PAYMENT_MADE_AMOUNT_BY_PARTY_ID";

}
